sudo: false
language: node
script:
- echo "No Script to run"
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: Node2
  default: true
  no_promote: true
  on:
    all_branches: master
